version: '3.7'

services:
    mongodb:
        image: mongo
        ports:
          - '27017:27017'
        volumes: 
          - ./data:/data/db
        networks: 
          - epsilon-compose-network                
    api:
        build:
          context: ./services/api-graphql
          dockerfile: Dockerfile.dev
        depends_on:
          - mongodb
        ports:
          - "4000:4000"
        command: "npm run dev"
        
        volumes:
          - type: bind
            source: ./services/api-graphql
            target: /app
        working_dir: /app
        networks: 
          - epsilon-compose-network

networks:
  epsilon-compose-network:
    driver: bridge
